### ISSUE TITLE
go get report errors

### ISSUE THREAD

**Issue by ttzc** [sbinet/go-python#101]
Wrong information：
# go-python
In file included from .\capi.go:3:0:
./go-python.h:4:20: fatal error: Python.h: No such file or directory
 #include "Python.h"
                    ^
compilation terminated

**Comment by huangll** [comment]
I got the same mistake。
I‘m build on windows 10.

**Comment by EldersJavas** [comment]
same
```powershell
# github.com/sbinet/go-python
In file included from D:\GOPATH\pkg\mod\github.com\sbinet\go-python@v0.1.0\capi.go:3:
./go-python.h:4:10: fatal error: Python.h: No such file or directory
    4 | #include "Python.h"
      |          ^~~~~~~~~~
compilation terminated.

**Comment by EniMusguera** [comment]
what can i do ?

**Comment by sbinet** [comment]
instructions for the compilation failures are noted on the `README`:

- https://github.com/sbinet/go-python#install

these compilation failures usually boil down to `cgo` not being able to locate the CPython development headers.
one needs to:

- make sure these development headers are properly installed
  _e.g.:_ `apt install python2-dev` on a Debian-like distribution
- make sure these development headers can be found by `cgo` (either by installing `pkgconfig` support files for CPython2, or by editing `cgoflags.go` in `go-python`)
