### ISSUE TITLE
Error reporting for execute command under win10

### ISSUE THREAD

**Issue by Suceru** [sbinet/go-python#109]
Error reporting for execute command under win10

```
C:\Users\12464> go get github.com/sbinet/go-python
# github.com/sbinet/go-python
In file included from D:\Go\src\github.com\sbinet\go-python\capi.go:3:
./go-python.h:4:10: fatal error: Python.h: No such file or directory
 #include "Python.h"
          ^~~~~~~~~~
```
The python installation directory is ` C:\Users\12464\AppData\Local\Programs\Python\Python38`
include directory is `C:\Users\12464\AppData\Local\Programs\Python\Python38\include`

**Comment by Tachy0nOwO** [comment]
I met the same problem, could you tell me the solution if you solve it?

**Comment by equisde** [comment]
i have this exact problem my install directory is `C:\Python39` include is in `C:\Python39\include`

**Comment by sbinet** [comment]
`sbinet/go-python` is for CPython-2.

you can try https://github.com/DataDog/go-python3 for CPython-3.
