### ISSUE TITLE
Documentation not displayed due to license restrictions.

### ISSUE THREAD

**Issue by ggandycong** [sbinet/go-python#113]
The documentation on go-python is not being displayed correctly due to license restrictions.
https://pkg.go.dev/github.com/sbinet/go-python
> Documentation not displayed due to license restrictions.See our license policy.

please how to read the doc ?

**Comment by sbinet** [comment]
well, `pkg.go.dev` chokes on CPython's license (that `go-python` dutifully uses: CPython2's is released under the GPL license and as such -as go-python is linked against that C-API+lib- go-python is released under the same terms)

a possible workaround is to use godocs.io:

- https://godocs.io/github.com/sbinet/go-python

**Comment by sbinet** [comment]
that said, I'll change the link on the README.
