### ISSUE TITLE
fdopen doesn't work on Windows

### ISSUE THREAD

**Issue by Jragonmiris** [sbinet/go-python#21]
Write now in `object.go` it uses file.Fd and C.fdopen. Unfortunately, fdopen doesn't work on windows.

It seems to work for me if I exchange it with

    // ...
    name := C.CString(file.Name())
    defer C.free(unsafe.Pointer(name))
    C.fopen(name, cmode)
    // ...

But I'm not confident it will always work. I'm not sure if anything can be done, AFAIK the WIndows equivalent to fdopen is pretty gnarly.

**Comment by sbinet** [comment]
thanks for the report.
I left ``fdopen`` for POSIX platforms and went with ``fopen`` on windows.
