### ISSUE TITLE
Quick spelling update

### ISSUE THREAD

**Issue by asyncsrc** [sbinet/go-python#23]
As a friendly suggestion, it might be worth updating the first word in the README.md file from _naive_ to _native_ .

**Comment by sbinet** [comment]
I am not a native speaker so I always welcome fixes in that department, but in that particular occurence, I think it means what I meant:
http://dictionary.reference.com/browse/naive

```
having or showing unaffected simplicity of nature or absence of artificiality; 
**unsophisticated;**
ingenuous.
```
