### ISSUE TITLE
PyFloat_FromDouble should take a float64

### ISSUE THREAD

**Issue by zjb0807** [sbinet/go-python#43]
// PyObject* PyFloat_FromDouble(double v) 
// Return value: New reference.
// Create a PyFloatObject object from v, or NULL on failure.
func PyFloat_FromDouble(v float32) *PyObject {
    return togo(C.PyFloat_FromDouble(C.double(v)))
}

**Comment by zjb0807** [comment]
another question, when i use PyFloat_AsDouble function:
err: cannot use python.PyFloat_AsDouble(rate) (type float64) as type float32 in assignment

**Comment by sbinet** [comment]
`python.PyFloat_AsDouble` now returns a `float64`.
either change the type of the value being assigned to (from `float32` to `float64`) or convert what `python.PyFloat_AsDouble` returns to a `float32`.
