### ISSUE TITLE
Python calls go function

### ISSUE THREAD

**Issue by zjb0807** [sbinet/go-python#44]
In go source:
//------------------------------
type mdapi struct {
}
func (p *mdapi)add(){}
//------------------------------
how to call add function in python code ?

**Comment by zjb0807** [comment]
In go source:


how to call add in python code ?

**Comment by sbinet** [comment]
theoretically, you should simply have to follow: https://docs.python.org/2/extending/extending.html#a-simple-example

but that's not easily possible with `go-python` (especially the `PyMethodDef` and `Py_InitModule` parts)

I would recommand [github.com/go-python/gopy](https://github.com/go-python/gopy) if you are using `go-1.5` (`gopy` isn't completely compatible with `go >= 1.6`)
