### ISSUE TITLE
go-python together with a minimal (or as minimal as possible) reproducer

### ISSUE THREAD

**Issue by zjb0807** [sbinet/go-python#45]
use "go-python" call python function, the program will coredump
![2](https://cloud.githubusercontent.com/assets/16496415/17640162/3d0c1738-612d-11e6-9d60-1795a6705dcc.jpg)

**Comment by zjb0807** [comment]
this is coredump file:
![c789ffd6 c3f6506c 22a6ad57_recompress](https://cloud.githubusercontent.com/assets/16496415/17640209/dacaf02a-612d-11e6-8096-4331cee75b45.jpg)

**Comment by sbinet** [comment]
thanks for the report but, to help you, I would need some code and instructions for me to reproduce the crash.

**Comment by zjb0807** [comment]
it was a bug in my code, thank you
