### ISSUE TITLE
could not import 'kwargs'

### ISSUE THREAD

**Issue by zznan0o0** [sbinet/go-python#58]
excuse me
I'm run the example of  kw-args and modify-values under the tests but error: 
importing kwargs...
2017/10/14 05:47:31 could not import 'kwargs'
exit status 1

the other is the same

i'm ubuntu 16.04， Python 2.7.12， go 1.6

**Comment by jjjachyty** [comment]
add this code before	your  `fmt.Printf("importing kwargs...\n")`
```
python.PyRun_SimpleString("import sys")
	python.PyRun_SimpleString("sys.path.append('/DATA/Work/CODE/GO/GOPATH/src/github.com/sbinet/go-python/tests/kw-args')")
```

**Comment by sbinet** [comment]
adding it from the `go-python.Initialize` function would be a bit unpolite.

another simple way is to add `.` (or any other directory) to `$PYTHONPATH`.
