### ISSUE TITLE
python3 support

### ISSUE THREAD

**Issue by ruyuejun** [sbinet/go-python#93]
When the project will support python3 ?

**Comment by sbinet** [comment]
the plan was to migrate this repo under `github.com/go-python/cpy2` and then create a dedicated repo `go-python/cpy3`.

**Comment by sbinet** [comment]
there's also:
- https://github.com/DataDog/go-python3
(which is - IIUC - a fork of this repo to migrate to CPython3)

**Comment by okpatil4u** [comment]
It would be great if Python 3 is supported as Python 2 will be obsolete in December. How would one port it to Python 3 ?

**Comment by sbinet** [comment]
https://github.com/DataDog/go-python3 already supports CPython3.
from their README, it seems this was the port of this repo to the CPython3 API. so, kind of already done :)
