### ISSUE TITLE
How to use Py_Main function init to python3.X

### ISSUE THREAD

**Issue by viney** [sbinet/go-python#95]
package main

import (
        "os"

        "github.com/sbinet/go-python"
)

func init() {
        if err := python.Initialize(); err != nil {
                panic(err)
        }
}

func main(){
        rc:=python.Py_Main(os.Args)
        os.Exit(rc)
}

default open python2.7 in ubuntu16.04

**Comment by sbinet** [comment]
`sbinet/go-python` only supports CPython2.

for CPython3, you may want to look at:
https://github.com/DataDog/go-python3
